###---Posts APIs---###

###Add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "content": "This is my first post",
  "sender": "Ofri and Amit2"
}

###Get all posts
GET http://localhost:3000/posts

###Get a post by ID
GET http://localhost:3000/posts/69664be940e026879eb78545

###Get a post by sender
GET http://localhost:3000/posts/sender/Ofri and Amit

###Update a post by ID
PUT http://localhost:3000/posts/69664be940e026879eb78545
Content-Type: application/json

{
  "content": "This is my updated post content",
  "sender": "Ofri and Amit"
}



###---Comments APIs---###

###Add a new comment to a post
POST http://localhost:3000/posts/69664be940e026879eb78545/comments
Content-Type: application/json

{
  "content": "This is a comment on the post",
  "sender": "Amit and Ofri"
}

###Get all comments for a specific post
GET http://localhost:3000/posts/69664be940e026879eb78545/comments

###Get a comment by ID
GET http://localhost:3000/posts/comments/696babd4d58d1ce4ff12ec90

###Update a comment by ID
PUT http://localhost:3000/posts/comments/696babd4d58d1ce4ff12ec90
Content-Type: application/json

{
  "content": "This is my updated comment content",
  "sender": "Ami1t and Ofri1"
}


