###---Posts APIs---###

###Add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "content": "This is my first post",
  "sender": "Ofri and Amit"
}

###Get all posts
GET http://localhost:3000/posts

###Get a post by ID
GET http://localhost:3000/posts/69664be940e026879eb78545

###Get a post by sender
GET http://localhost:3000/posts/sender/Ofri and Amit

###Update a post by ID
PUT http://localhost:3000/posts/69664be940e026879eb78545
Content-Type: application/json

{
  "content": "This is my updated post content",
  "sender": "Ofri and Amit"
}



###---Comments APIs---###